name: Build Docker image

on:
  push:
    branches:
      - arm64-support

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker buildx create --use
      - run: docker buildx build --platform linux/amd64,linux/arm64 .
